<?php

/**
 * @file
 * Install, update, and uninstall functions for the subpathauto module.
 */

/**
 * Convert Sub-path Auto settings to config.
 */
function subpathauto_update_1000() {
  $config = config('subpathauto.settings');
  $config->set('ignore_admin', update_variable_get('subpathauto_ignore_admin', 1));
  $config->set('depth', update_variable_get('subpathauto_depth', 1));
  $config->save();
  update_variable_del('subpathauto_ignore_admin');
  update_variable_del('subpathauto_depth');
}
